version: '3.8'

services:
  # PostgreSQL 数据库（user-service）
  postgres:
    image: postgres:14-alpine
    container_name: todolist-postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todolist-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MySQL 数据库（todo-service）
  mysql:
    image: mysql:8.0
    container_name: todolist-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tododb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todolist-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # User Service (Python/FastAPI)
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: todolist-user-service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/userdb
      SECRET_KEY: your-secret-key-change-in-production
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:19006
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todolist-network
    restart: unless-stopped

  # Todo Service (Java/Spring Boot)
  todo-service:
    build:
      context: ./todo-service
      dockerfile: Dockerfile
    container_name: todolist-todo-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tododb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      USER_SERVICE_URL: http://user-service:8001
    ports:
      - "8002:8002"
    depends_on:
      mysql:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
      - todolist-network
    restart: unless-stopped

volumes:
  postgres_data:
  mysql_data:

networks:
  todolist-network:
    driver: bridge
