# 生产环境配置
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

user-service:
  url: ${USER_SERVICE_URL}

logging:
  level:
    com.todolist.todoservice: INFO
    org.springframework.web: WARN
